### PR TITLE
Error thrown with Preact8

### PR DESCRIPTION
**Pull request by dharFr**
While testing `preact@8` within our existing code base, we encountered the following error :
css-transition-group-preact8

As far as I understand, `preact@8` components might receive an array containing `null` values (e.g. `[null]`) as `children` property while it never happened in the previous versions.

This PR attempts to fix the compatibility with `preact@8`:
 - The first commit add a test case that reproduce our use case. The test pass when running `npm test` or `PREACT_VERSION=7.2.0 npm test` but fails with `PREACT_VERSION=8.1.0 npm test`
 - The second commit attempts to fix the issue by filtering out the `null` entries that might be received in the `children` prop. Please tell me if it's a good approach or not.
 - *_EDIT_* : I also added version `7.2.1` and `8.1.0` to `travis.yml` in the last commit, so the test is actually ran on the appropriate versions.

### CODE REVIEW

**Comment by developit** [comment]
Wow, this is a flawless PR. Thanks dude.

**Review by developit — APPROVED** [review]

**Comment by dharFr** [comment]
You're welcome!
Thanks for merging it so fast 🤘

**Comment by dharFr** [comment]
@developit Any chance for the fix to be released on npm?

**Comment by developit** [comment]
Yup!

**Comment by developit** [comment]
Released as [1.2.0](https://github.com/developit/preact-css-transition-group/releases/tag/1.2.0) 👍 
Thanks again for the great PR.

**Pull request merged**
